### ISSUE TITLE
Best Practice for Implementing Silence-as-Consent with Filament Approvals

### ISSUE THREAD

**Issue by digitall-it** [eighty9nine/filament-approvals#36]
I am looking for guidance on implementing a "silence-as-consent" mechanism using the Filament Approvals plugin. My goal is to have an approval request automatically considered approved (or rejected) if the agent does not respond within a given time frame.

What would be the recommended way to implement this behavior using the plugin? Any examples or best practices would be very helpful.

Thank you for your assistance!

**Comment by eighty9nine** [comment]
# Implementing Silence-as-Consent with Filament Approvals Plugin

## Overview

The "silence-as-consent" mechanism allows approval requests to be automatically approved (or rejected) if the designated approver doesn't respond within a specified timeframe. This guide provides comprehensive guidance on implementing this behavior with the Filament Approvals plugin.

## Current Plugin Architecture

The Filament Approvals plugin is built on top of the `ringlesoft/laravel-process-approval` package and provides:

- **Approval Flows**: Define multi-step approval processes
- **Approval Steps**: Role-based approval stages
- **Action States**: Submit, Approve, Reject, Discard
- **Status Tracking**: Monitor approval progress

## Implementation Strategies

### 1. Database Schema Extensions

First, you'll need to extend the approval system to track timing information:

#### Create Migration for Timeout Configuration

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up()
    {
        // Add timeout configuration to approval steps
        Schema::table('process_approval_flow_steps', function (Blueprint $table) {
            $table->integer('timeout_hours')->nullable()->after('action');
            $table->enum('timeout_action', ['approve', 'reject'])->default('approve')->after('timeout_hours');
        });

        // Add timeout tracking to approval status
        Schema::table('process_approval_statuses', function (Blueprint $table) {
            $table->timestamp('current_step_started_at')->nullable()->after('updated_at');
            $table->timestamp('timeout_at')->nullable()->after('current_step_started_at');
        });
    }

    public function down()
    {
        Schema::table('process_approval_flow_steps', function (Blueprint $table) {
            $table->dropColumn(['timeout_hours', 'timeout_action']);
        });

        Schema::table('process_approval_statuses', function (Blueprint $table) {
            $table->dropColumn(['current_step_started_at', 'timeout_at']);
        });
    }
};
```

### 2. Extend Approval Flow Configuration

#### Enhanced StepsRelationManager

Create a custom relation manager to include timeout configuration:

```php
<?php

namespace App\Filament\Resources\ApprovalFlowResource\RelationManagers;

use EightyNine\Approvals\Filament\Resources\ApprovalFlowResource\RelationManagers\StepsRelationManager as BaseStepsRelationManager;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Form;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class StepsRelationManager extends BaseStepsRelationManager
{
    public function form(Form $form): Form
    {
        return $form
            ->columns(12)
            ->schema([
                Select::make("role_id")
                    ->searchable()
                    ->label("Role")
                    ->helperText("Who should approve in this step?")
                    ->options(fn() => ((string) config('process_approval.roles_model'))::get()
                        ->map(fn ($model) => [
                            "name" => str($model->name)
                                ->replace("_", " ")
                                ->title()
                                ->toString(),
                            "id" => $model->id
                        ])->pluck("name", "id"))
                    ->columnSpan(4)
                    ->native(false),
                
                Select::make("action")
                    ->helperText("What should be done in this step?")
                    ->native(false)
                    ->default("APPROVE")
                    ->columnSpan(3)
                    ->options([
                        'APPROVE' => __('filament-approvals::approvals.actions.approve'),
                        'VERIFY' =>  __('filament-approvals::approvals.actions.verify'),
                        'CHECK' => __('filament-approvals::approvals.actions.check'),
                    ]),
                
                TextInput::make('timeout_hours')
                    ->label('Timeout (Hours)')
                    ->helperText('Auto-action after this many hours of inactivity')
                    ->type('number')
                    ->columnSpan(2)
                    ->nullable(),
                
                Select::make('timeout_action')
                    ->label('Timeout Action')
                    ->helperText('Action to take when timeout expires')
                    ->options([
                        'approve' => 'Auto-Approve',
                        'reject' => 'Auto-Reject',
                    ])
                    ->default('approve')
                    ->columnSpan(2)
                    ->visible(fn($get) => $get('timeout_hours')),
                
                TextInput::make('order')
                    ->label('Order')
                    ->type('number')
                    ->columnSpan(1)
                    ->default(fn($livewire) => $livewire->ownerRecord->steps->count() + 1)
            ]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->recordTitleAttribute('id')
            ->reorderable("order")
            ->defaultSort('order', 'asc')
            ->columns([
                TextColumn::make('order')->label('Order'),
                TextColumn::make('role.name'),
                TextColumn::make('action'),
                TextColumn::make('timeout_hours')
                    ->label('Timeout (Hours)')
                    ->placeholder('No timeout'),
                TextColumn::make('timeout_action')
                    ->label('Timeout Action')
                    ->badge()
                    ->color(fn($state) => $state === 'approve' ? 'success' : 'danger'),
            ])
            ->filters([
                //
            ])
            ->headerActions([
                \Filament\Tables\Actions\CreateAction::make()
                    ->icon('heroicon-s-plus')
                    ->label(__('filament-approvals::approvals.actions.add_step')),
            ])
            ->actions([
                \Filament\Tables\Actions\EditAction::make(),
                \Filament\Tables\Actions\DeleteAction::make(),
            ])
            ->bulkActions([
                \Filament\Tables\Actions\BulkActionGroup::make([
                    \Filament\Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }
}
```

### 3. Enhanced Approvable Trait

Extend the existing `Approvable` trait to handle timeouts:

```php
<?php

namespace App\Traits;

use EightyNine\Approvals\Traits\Approvable as BaseApprovable;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use RingleSoft\LaravelProcessApproval\Models\ProcessApproval;

trait ApprovableWithTimeout
{
    use BaseApprovable;

    /**
     * Submit the model and set timeout tracking
     */
    public function submit($user = null): bool
    {
        $result = parent::submit($user ?? Auth::user());
        
        if ($result) {
            $this->setCurrentStepTimeout();
        }
        
        return $result;
    }

    /**
     * Approve and update timeout for next step
     */
    public function approve(string $comment = null, $user = null): bool
    {
        $result = parent::approve($comment, $user ?? Auth::user());
        
        if ($result && !$this->isApprovalCompleted()) {
            $this->setCurrentStepTimeout();
        }
        
        return $result;
    }

    /**
     * Set timeout for current approval step
     */
    protected function setCurrentStepTimeout(): void
    {
        $currentStep = $this->getCurrentApprovalStep();
        
        if ($currentStep && $currentStep->timeout_hours) {
            $this->approvalStatus->update([
                'current_step_started_at' => now(),
                'timeout_at' => now()->addHours($currentStep->timeout_hours),
            ]);
        }
    }

    /**
     * Get the current approval step configuration
     */
    public function getCurrentApprovalStep()
    {
        if (!$this->approvalStatus) {
            return null;
        }

        $steps = collect($this->approvalStatus->steps ?? []);
        $currentStepIndex = $steps->search(function ($step) {
            return $step['process_approval_action'] === null;
        });

        if ($currentStepIndex === false) {
            return null;
        }

        $flow = $this->approvalStatus->approvalFlow;
        return $flow->steps()->where('order', $currentStepIndex + 1)->first();
    }

    /**
     * Check if current step has timed out
     */
    public function hasCurrentStepTimedOut(): bool
    {
        if (!$this->approvalStatus || !$this->approvalStatus->timeout_at) {
            return false;
        }

        return now()->isAfter($this->approvalStatus->timeout_at);
    }

    /**
     * Get timeout information for display
     */
    public function getTimeoutInfo(): ?array
    {
        $currentStep = $this->getCurrentApprovalStep();
        
        if (!$currentStep || !$currentStep->timeout_hours || !$this->approvalStatus->timeout_at) {
            return null;
        }

        return [
            'timeout_at' => $this->approvalStatus->timeout_at,
            'hours_remaining' => max(0, now()->diffInHours($this->approvalStatus->timeout_at, false)),
            'timeout_action' => $currentStep->timeout_action,
            'is_overdue' => $this->hasCurrentStepTimedOut(),
        ];
    }

    /**
     * Process timeout action
     */
    public function processTimeout(): bool
    {
        if (!$this->hasCurrentStepTimedOut()) {
            return false;
        }

        $currentStep = $this->getCurrentApprovalStep();
        
        if (!$currentStep) {
            return false;
        }

        $comment = "Automatically {$currentStep->timeout_action}d due to timeout after {$currentStep->timeout_hours} hours";
        
        if ($currentStep->timeout_action === 'approve') {
            return $this->approve($comment, null);
        } else {
            return $this->reject($comment, null);
        }
    }
}
```

### 4. Scheduled Command for Processing Timeouts

Create an Artisan command to process expired approvals:

```php
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Database\Eloquent\Builder;
use RingleSoft\LaravelProcessApproval\Models\ProcessApprovalStatus;

class ProcessApprovalTimeouts extends Command
{
    protected $signature = 'approvals:process-timeouts';
    protected $description = 'Process approval timeouts and auto-approve/reject expired requests';

    public function handle()
    {
        $expiredApprovals = ProcessApprovalStatus::query()
            ->whereNotNull('timeout_at')
            ->where('timeout_at', '<=', now())
            ->where('status', 'PENDING')
            ->get();

        $processed = 0;
        $failed = 0;

        foreach ($expiredApprovals as $approvalStatus) {
            try {
                $model = $approvalStatus->approvable;
                
                if ($model && method_exists($model, 'processTimeout')) {
                    if ($model->processTimeout()) {
                        $processed++;
                        $this->info("Processed timeout for {$model->getMorphClass()} ID: {$model->id}");
                    }
                }
            } catch (\Exception $e) {
                $failed++;
                $this->error("Failed to process timeout for approval ID {$approvalStatus->id}: {$e->getMessage()}");
            }
        }

        $this->info("Processed {$processed} timeouts, {$failed} failures");
        
        return Command::SUCCESS;
    }
}
```

### 5. Enhanced Status Column with Timeout Display

Create a custom status column that shows timeout information:

```php
<?php

namespace App\Tables\Columns;

use EightyNine\Approvals\Tables\Columns\ApprovalStatusColumn as BaseApprovalStatusColumn;

class ApprovalStatusColumnWithTimeout extends BaseApprovalStatusColumn
{
    protected string $view = 'tables.columns.approval-status-column-with-timeout';
}
```

Create the corresponding Blade view `resources/views/tables/columns/approval-status-column-with-timeout.blade.php`:

```blade
<div>
    @if($getRecord()->approvalStatus)
        <p class="px-3">
            <small>
                @if ($getRecord()->isApprovalCompleted())
                    {{ __('filament-approvals::approvals.status_column.approval_complete') }} {{ __('filament-approvals::approvals.status_column.approval_by_prefix') }}
                    @if ($getRecord()->lastApproval)
                        {{ $getRecord()->lastApproval->approver_name }}
                    @else
                        {{ $getRecord()->createdBy()->name }}
                    @endif
                @else
                    {{ $getRecord()->approvalStatus->status }} {{ __('filament-approvals::approvals.status_column.approval_by_prefix') }}
                    @if ($getRecord()->nextApprover)
                        {{ $getRecord()->nextApprover->name }}
                    @else
                        {{ $getRecord()->createdBy()->name }}
                    @endif
                @endif
            </small>
        </p>
        
        @php
            $timeoutInfo = method_exists($getRecord(), 'getTimeoutInfo') ? $getRecord()->getTimeoutInfo() : null;
        @endphp
        
        @if($timeoutInfo)
            <p class="px-3 text-xs">
                <small class="{{ $timeoutInfo['is_overdue'] ? 'text-red-600' : 'text-yellow-600' }}">
                    @if($timeoutInfo['is_overdue'])
                        ⚠️ Overdue ({{ $timeoutInfo['timeout_action'] }} pending)
                    @else
                        ⏰ Auto-{{ $timeoutInfo['timeout_action'] }} in {{ $timeoutInfo['hours_remaining'] }}h
                        <br>
                        <span class="text-gray-500">Expires: {{ $timeoutInfo['timeout_at']->format('M j, Y g:i A') }}</span>
                    @endif
                </small>
            </p>
        @endif
        
        <p class="px-3 text-xs">
            <small>
                {{ $getRecord()->isApprovalCompleted() ?
                    __('filament-approvals::approvals.status_column.approval_complete') :
                    __('filament-approvals::approvals.status_column.approval_in_process') }}
            </small>
        </p>
    @else
        <span class="px-3 py-1 bg-gray-200 text-gray-800 rounded-full text-xs">
            {{ __('filament-approvals::approvals.status_column.approval_status_does_not_exist') }}
        </span>
    @endif
</div>
```

### 6. Notification System for Approaching Timeouts

Create a notification to warn approvers of approaching deadlines:

```php
<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class ApprovalTimeoutWarning extends Notification
{
    use Queueable;

    public function __construct(
        protected $approvableModel,
        protected $hoursRemaining
    ) {}

    public function via($notifiable): array
    {
        return ['mail', 'database'];
    }

    public function toMail($notifiable): MailMessage
    {
        $modelName = class_basename($this->approvableModel);
        
        return (new MailMessage)
            ->subject("Approval Required: {$modelName} #{$this->approvableModel->id}")
            ->line("You have a pending approval that will auto-process in {$this->hoursRemaining} hours.")
            ->line("Model: {$modelName}")
            ->line("ID: {$this->approvableModel->id}")
            ->action('Review Approval', url("/admin/{$modelName}s/{$this->approvableModel->id}"))
            ->line('Please review and take action before the timeout expires.');
    }

    public function toArray($notifiable): array
    {
        return [
            'model_type' => get_class($this->approvableModel),
            'model_id' => $this->approvableModel->id,
            'hours_remaining' => $this->hoursRemaining,
        ];
    }
}
```

### 7. Enhanced Console Command with Warnings

Extend the timeout processing command to send warnings:

```php
<?php

namespace App\Console\Commands;

use App\Notifications\ApprovalTimeoutWarning;
use Illuminate\Console\Command;
use RingleSoft\LaravelProcessApproval\Models\ProcessApprovalStatus;

class ProcessApprovalTimeouts extends Command
{
    protected $signature = 'approvals:process-timeouts {--warn-hours=24 : Hours before timeout to send warning}';
    protected $description = 'Process approval timeouts and send warnings';

    public function handle()
    {
        $warnHours = $this->option('warn-hours');
        
        // Process expired timeouts
        $this->processExpiredTimeouts();
        
        // Send warnings for approaching timeouts
        $this->sendTimeoutWarnings($warnHours);
        
        return Command::SUCCESS;
    }

    protected function processExpiredTimeouts()
    {
        $expiredApprovals = ProcessApprovalStatus::query()
            ->whereNotNull('timeout_at')
            ->where('timeout_at', '<=', now())
            ->where('status', 'PENDING')
            ->get();

        $processed = 0;
        $failed = 0;

        foreach ($expiredApprovals as $approvalStatus) {
            try {
                $model = $approvalStatus->approvable;
                
                if ($model && method_exists($model, 'processTimeout')) {
                    if ($model->processTimeout()) {
                        $processed++;
                        $this->info("Processed timeout for {$model->getMorphClass()} ID: {$model->id}");
                    }
                }
            } catch (\Exception $e) {
                $failed++;
                $this->error("Failed to process timeout: {$e->getMessage()}");
            }
        }

        $this->info("Processed {$processed} timeouts, {$failed} failures");
    }

    protected function sendTimeoutWarnings($warnHours)
    {
        $approachingTimeouts = ProcessApprovalStatus::query()
            ->whereNotNull('timeout_at')
            ->where('timeout_at', '>', now())
            ->where('timeout_at', '<=', now()->addHours($warnHours))
            ->where('status', 'PENDING')
            ->whereDoesntHave('notifications', function($query) use ($warnHours) {
                $query->where('type', ApprovalTimeoutWarning::class)
                      ->where('created_at', '>=', now()->subHours($warnHours));
            })
            ->get();

        $warningsSent = 0;

        foreach ($approachingTimeouts as $approvalStatus) {
            try {
                $model = $approvalStatus->approvable;
                $nextApprover = $model->nextApprover ?? $model->createdBy();
                $hoursRemaining = now()->diffInHours($approvalStatus->timeout_at);

                if ($nextApprover) {
                    $nextApprover->notify(new ApprovalTimeoutWarning($model, $hoursRemaining));
                    $warningsSent++;
                }
            } catch (\Exception $e) {
                $this->error("Failed to send warning: {$e->getMessage()}");
            }
        }

        $this->info("Sent {$warningsSent} timeout warnings");
    }
}
```

### 8. Scheduling Configuration

Add to your `app/Console/Kernel.php`:

```php
protected function schedule(Schedule $schedule)
{
    // Process timeouts every 15 minutes
    $schedule->command('approvals:process-timeouts')
             ->everyFifteenMinutes()
             ->withoutOverlapping();
             
    // Send warnings twice daily
    $schedule->command('approvals:process-timeouts --warn-hours=24')
             ->twiceDaily(9, 15);
}
```

## Implementation Checklist

### Phase 1: Basic Timeout Infrastructure
- [ ] Create database migrations for timeout fields
- [ ] Extend Approvable trait with timeout methods
- [ ] Create basic timeout processing command
- [ ] Set up scheduled task

### Phase 2: UI Enhancements
- [ ] Extend StepsRelationManager for timeout configuration
- [ ] Create enhanced status column with timeout display
- [ ] Update approval flow forms
- [ ] Add timeout info to approval history

### Phase 3: Advanced Features
- [ ] Implement warning notification system
- [ ] Create timeout dashboard/reporting
- [ ] Add manual timeout override capabilities
- [ ] Implement role-based timeout escalation

### Phase 4: Testing & Monitoring
- [ ] Write unit tests for timeout logic
- [ ] Create integration tests for full workflow
- [ ] Set up monitoring for timeout processing
- [ ] Document configuration options

## Configuration Options

### Environment Variables

```env
# Default timeout warning hours
APPROVAL_TIMEOUT_WARNING_HOURS=24

# Enable/disable timeout processing
APPROVAL_TIMEOUT_ENABLED=true

# Timeout processing frequency (cron expression)
APPROVAL_TIMEOUT_SCHEDULE="*/15 * * * *"
```

### Config File Extension

Add to `config/approvals.php`:

```php
return [
    // ... existing config ...
    
    'timeout' => [
        'enabled' => env('APPROVAL_TIMEOUT_ENABLED', true),
        'warning_hours' => env('APPROVAL_TIMEOUT_WARNING_HOURS', 24),
        'default_timeout_hours' => 72, // 3 days default
        'max_timeout_hours' => 720, // 30 days maximum
        'notification_channels' => ['mail', 'database'],
    ],
];
```

## Best Practices

### 1. Timeout Duration Guidelines
- **Urgent approvals**: 4-8 hours
- **Standard approvals**: 24-72 hours  
- **Complex approvals**: 3-7 days
- **Executive approvals**: 5-10 days

### 2. User Experience Considerations
- Always show remaining time clearly
- Send warnings at 75%, 90%, and 95% of timeout period
- Provide easy override mechanisms for administrators
- Log all timeout actions for audit trails

### 3. Error Handling
- Gracefully handle timeout processing failures
- Implement retry mechanisms for failed notifications
- Maintain detailed logs of all timeout activities
- Provide manual intervention capabilities

### 4. Performance Optimization
- Index timeout_at fields for efficient queries
- Batch process multiple timeouts
- Use background jobs for notification sending
- Monitor command execution time

## Troubleshooting

### Common Issues

1. **Timeouts not processing**: Check cron job configuration and command logs
2. **Missing notifications**: Verify notification channels and user preferences
3. **Incorrect timeout calculations**: Ensure timezone settings are correct
4. **Performance issues**: Check database indexes and query efficiency

### Debugging Commands

```bash
# Test timeout processing manually
php artisan approvals:process-timeouts --verbose

# Check for pending timeouts
php artisan tinker
>>> ProcessApprovalStatus::whereNotNull('timeout_at')->where('timeout_at', '<=', now())->count()

# View timeout configuration
php artisan config:show approvals.timeout
```

## Security Considerations

1. **Audit Logging**: Log all timeout actions with user attribution
2. **Permission Checks**: Verify user permissions before auto-processing
3. **Rate Limiting**: Prevent abuse of timeout override features  
4. **Data Integrity**: Ensure timeout actions maintain data consistency

## Conclusion

Implementing silence-as-consent with the Filament Approvals plugin requires careful planning and attention to user experience. The approach outlined above provides a comprehensive foundation that can be customized based on your specific business requirements.

Remember to thoroughly test the implementation in a staging environment before deploying to production, and consider gradual rollout with monitoring to ensure the system performs as expected.
